sudo: required
language: minimal
dist: xenial
script:
- make tests
before_deploy:
- curl -sSL https://raw.githubusercontent.com/Victor-Savu/poetry/patch-1/get-poetry.py | python
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
- poetry build
deploy:
  provider: script
  script: poetry publish
  on:
    tags: true
