language: minimal
dist: xenial
script:
- make tests
deploy:
  provider: script
  script: make publish
  on:
    tags: true
env:
  global:
    - secure: "TzEQUm8wXCHnq+JiDDskIvp4cW4IF0d7EqBi5/aWl8rwhZz/Baj8UgoeiLQN4iUNP+bduy7xYkqFeWcjNSZkQxFNmK1zZxbQ86N67aUCt9kYASbkbZF+nBUhceiMdOhRC7J2z32qtBXFhST9e0iGAuR1FGXbTtBczdKF/6sJc3/PpUkLVAbEOu1C68E3i8REtNftKmVWCWmtTL2vkU34sApLp86cjawojhlEeKsZJUWKDLrNzAxlkag+MQ0Yncbfzll+HM/wqkgfNTrcndaUWl7uG+EA3ZoVKwmGbWBb0715xEJGNonH/rffIQ0tuqibrQm1RVfbpUGDssSOkbV0EZBidnu6pqCk2Jtd5Rh/NlFh/Vu4eO5sB6zEbw0SviGK/ZCar03f7UyRB20JrClxfVEO1LSDUM9Sa30IFLjPSs6zNdNDKYELgUH9+Oqd7rcPAZ0RY8o8Lu5szBiosdpg0bST8QdSzVqaBtALQ8yNRcrkcUrQTKn6pYnkeRBJbItVRZosFLMLukvlWj/M6MqECgXbo1Iis5wlHp53nk3+WahDgbLLhaewqyuz193ZdfQBhMeMLVJyXx+t34c5wBgDwxr/H2VyyvELkzEHR8ENmZNmQSZbXfTJI8ID1UBCGt6yzC2dGh3aeXcgaExr/e94cU12AHgm7WwOxEnzF9qR2E4="
    - secure: "vYNi+F0x1GsIJSzd8iUYInlBSSL5ykktFoBXRDISz2frK3E4j2uai7ZDekex0HgUA5w8gjjORixyooTZXDzKrwfdbNHGo0iWJVeBY2Dn2gp9I+48ixC0bZ3TBiTtmBAbeyrbWx58QB7RPtFMRNhA7udOiLKR9+3o11FRP+M7WG5BxAA9hJKKPFzIKoAQXqur3mRLzG4rbPGB7++qzlBLb3XgJu+5oTG5kHLcDzRzSNc1kIGjuGcfEa/byoc2wG2SsanAHI0FiscsXJl0skNxpKF+Z96nuADRIF2FSBU9VOy5MZ2Nz/b4hpQxXa6RM9TA6TYYHSnS8s8URlYomxOSwGuSy9lasLPeiDJD47cDoIGF8OEoMCSoPPdOuWeoCPMm5p6G4I0q7R3914xpoAoTXC1AFeaP8suAcuyS5X7z5I9rNSMFE2HD2iB2uftDBsRD+FlbfBSsYcZ3IuSDvPYaxz5m76K2oYsMVZw+KYNqMewrsyCfSNCYvF2DBSbAHAY8n+lLdAd77T7Paxx4cEEe7ESU8KUNgE633U4ZLjeU58eHS4+IbsXyX5G16Ca2WZRE+mrjYJKYmmCoymALiGavyxkM+xgoQMdVbIieg0hE2yc9CO7HFlpq6kRaHwg9ytBIYCF3xsrAg9bpql+b0YFAW7Eqg+Ixrjf2+Sm7deKSPlQ="
